name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Do not depend on openssl
        run: test -z "$( cargo tree --prefix none | grep openssl )"
      - name: Lint & test
        run: |
          cargo clippy -- -D warnings
          # Skip tests affected by blocklisting on GitHub runners
          cargo test -- \
            --skip detects_my_domain_as_invalid \
            --skip endler \
            --skip tuta \
            --skip icloud
